name: Tests

on: push

jobs:
  lint:
    name: Run tests
    runs-on: ubuntu-latest
    container: 'node:10.16-jessie'
    steps:
    - uses: actions/checkout@v2
    - name: npm ci
      run: npm ci
    - name: npm test
      run: npm test